apiVersion: v1
kind: PersistentVolumeClaimList
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      namespace: nsolid
      name: nsolid-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: DeploymentList
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      labels:
        app: storage
      name: storage
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: storage
        spec:
          containers:
          - image: nodesource/nsolid-storage:boron-2.0.1
            name: storage
            ports:
            - containerPort: 4000
              name: api
            - containerPort: 9001
              name: command
            - containerPort: 9002
              name: data
            - containerPort: 9003
              name: bulk
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      name: console
      labels:
        app: console
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: console
        spec:
          containers:
            - name: console
              image: nodesource/nsolid-console:boron-2.0.1
              env:
              - name: NSOLID_CONSOLE_STORAGE_URL
                value: https://storage:4000
              ports:
                - containerPort: 3000
                  name: console
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      labels:
        app: nginx-secure-proxy
      name: nginx-secure-proxy
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: nginx-secure-proxy
        spec:
          containers:
          - image: nginx
            imagePullPolicy: Always
            name: nginx-secure-proxy
            ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            volumeMounts:
            - mountPath: /etc/nginx/
              name: nginx-config
            - mountPath: /etc/nginx/ssl/
              name: nginx-tls
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 30
              timeoutSeconds: 1
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 5
              timeoutSeconds: 1
          restartPolicy: Always
          volumes:
          - name: nginx-tls
            secret:
              secretName: nginx-tls
          - name: nginx-config
            configMap:
              name: nginx-config
